### ISSUE TITLE
missing "requirements.txt"

### ISSUE THREAD

**Issue by andreaolgiati** [philschmid/huggingface-llama-2-samples#1]
The `bitsandbytes` library is not installed in the container, so it should be mentioned in a `requirements.txt` in `./scripts/`

**Comment by andreaolgiati** [comment]
As well as `peft`

**Comment by philschmid** [comment]
Thats why the `requirements.txt` is in the source_dir. https://github.com/philschmid/huggingface-llama-2-samples/blob/master/training/scripts/requirements.txt 

Not sure what you mean with missing

**Comment by andreaolgiati** [comment]
Ack - I was blindly following the instructions at https://www.philschmid.de/sagemaker-llama2-qlora and, on that page, there is no mention of cloning the repo. It took me a while to realize that the code was actually here, and it had a `requirements.txt` . 

Maybe the blog should lead with cloning the repo.

**Comment by philschmid** [comment]
added something in the blog

**Comment by andreaolgiati** [comment]
Thank you.
