### ISSUE TITLE
Error in build_llama2_prompt() 

### ISSUE THREAD

**Issue by pleonova** [philschmid/huggingface-llama-2-samples#13]
@philschmid I think you might have a small typo in the `build_llama2_prompt()` function. In the final `else` block, the `message.append` should be `message['content']`.

The following then works to continue the chat conversation:
```
messages.append({"role": "bot",
                 "content": response[0]["generated_text"][len(prompt):]})

messages.append({"role": "user", 
                 "content": "Verify that the previous answer was accurate."})
```

**Comment by philschmid** [comment]
Hey @pleonova, 

Thank you thats correct! its fixed now.
