### ISSUE TITLE
Error running fine-tuning on SageMaker

### ISSUE THREAD

**Issue by abhyudit309** [philschmid/huggingface-llama-2-samples#17]
Hi, I'm facing this issue when following the fine-tuning example for Llama-2-13b-chat. This happens after it loads the model:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/ml/code/train_sagemaker.py:315 in <module>                              │
│                                                                              │
│   312 │   training_function(args)                                            │
│   313                                                                        │
│   314 if __name__ == "__main__":                                             │
│ ❱ 315 │   main()                                                             │
│                                                                              │
│ /opt/ml/code/train_sagemaker.py:312 in main                                  │
│                                                                              │
│   309                                                                        │
│   310 def main():                                                            │
│   311 │   args = parse_args()                                                │
│ ❱ 312 │   training_function(args)                                            │
│   313                                                                        │
│   314 if __name__ == "__main__":                                             │
│   315 │   main()                                                             │
│                                                                              │
│ /opt/ml/code/train_sagemaker.py:195 in training_function                     │
│                                                                              │
│   192 │   │   bnb_4bit_compute_dtype=torch.bfloat16,                         │
│   193 │   )                                                                  │
│   194 │                                                                      │
│ ❱ 195 │   model = AutoModelForCausalLM.from_pretrained(                      │
│   196 │   │   args.model_id,                                                 │
│   197 │   │   use_cache=False                                                │
│   198 │   │   if args.gradient_checkpointing                                 │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factor │
│ y.py:471 in from_pretrained                                                  │
│                                                                              │
│   468 │   │   │   )                                                          │
│   469 │   │   elif type(config) in cls._model_mapping.keys():                │
│   470 │   │   │   model_class = _get_model_class(config, cls._model_mapping) │
│ ❱ 471 │   │   │   return model_class.from_pretrained(                        │
│   472 │   │   │   │   pretrained_model_name_or_path, *model_args, config=con │
│   473 │   │   │   )                                                          │
│   474 │   │   raise ValueError(                                              │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py:2795  │
│ in from_pretrained                                                           │
│                                                                              │
│   2792 │   │   │   │   mismatched_keys,                                      │
│   2793 │   │   │   │   offload_index,                                        │
│   2794 │   │   │   │   error_msgs,                                           │
│ ❱ 2795 │   │   │   ) = cls._load_pretrained_model(                           │
│   2796 │   │   │   │   model,                                                │
│   2797 │   │   │   │   state_dict,                                           │
│   2798 │   │   │   │   loaded_state_dict_keys,  # XXX: rename?               │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py:3109  │
│ in _load_pretrained_model                                                    │
│                                                                              │
│   3106 │   │   │   │   # Skip the load for shards that only contain disk-off │
│   3107 │   │   │   │   if shard_file in disk_only_shard_files:               │
│   3108 │   │   │   │   │   continue                                          │
│ ❱ 3109 │   │   │   │   state_dict = load_state_dict(shard_file)              │
│   3110 │   │   │   │                                                         │
│   3111 │   │   │   │   # Mistmatched keys contains tuples key/shape1/shape2  │
│   3112 │   │   │   │   # matching the weights in the model.                  │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py:429   │
│ in load_state_dict                                                           │
│                                                                              │
│    426 │   """                                                               │
│    427 │   if checkpoint_file.endswith(".safetensors") and is_safetensors_av │
│    428 │   │   # Check format of the archive                                 │
│ ❱  429 │   │   with safe_open(checkpoint_file, framework="pt") as f:         │
│    430 │   │   │   metadata = f.metadata()                                   │
│    431 │   │   if metadata.get("format") not in ["pt", "tf", "flax"]:        │
│    432 │   │   │   raise OSError(                                            │
╰──────────────────────────────────────────────────────────────────────────────╯
NameError: name 'safe_open' is not defined

**Comment by philschmid** [comment]
Have you installed `safetensors`?

**Comment by abhyudit309** [comment]
How do I install it for the entry point script specified when creating the estimator?

**Comment by philschmid** [comment]
is [that](https://github.com/philschmid/sagemaker-huggingface-llama-2-samples/blob/master/training/scripts/requirements.txt) in your source dir?

**Comment by abhyudit309** [comment]
No, I just had the training scripts in my source dir. Moving the requirements.txt file there fixed it. Thanks!
