### ISSUE TITLE
No matching distribution found for peft==0.4.0

### ISSUE THREAD

**Issue by EtienneFerrandi** [philschmid/huggingface-llama-2-samples#21]
When I start the train job, I get this error. Here is my requirements.txt : 
transformers==4.6
peft==0.6
accelerate==0.21.0
bitsandbytes==0.40.2
safetensors>=0.3.1
tokenizers>=0.13.3

I modified the version of transformers because the previous version was not supported.

**Comment by philschmid** [comment]
What error are you getting?

**Comment by EtienneFerrandi** [comment]
Precisely this error :

Collecting transformers==4.6
  Downloading transformers-4.6.0-py3-none-any.whl (2.3 MB)
ERROR: Could not find a version that satisfies the requirement peft==0.4.0 (from versions: none)
ERROR: No matching distribution found for peft==0.4.0

**Comment by philschmid** [comment]
There is 0.4.0 https://pypi.org/project/peft/0.4.0/ why did you change transformers 4.6.0. this might be the issue.

**Comment by EtienneFerrandi** [comment]
Yes, it is, thank you.
